from typing import Literal

class QuadBinFromTile:
    def __init__(self) -> None: ...
    def __datafusion_scalar_udf__(self) -> object: ...

class QuadBinFromLonLat:
    def __init__(self) -> None: ...
    def __datafusion_scalar_udf__(self) -> object: ...

class QuadBinToParent:
    def __init__(self) -> None: ...
    def __datafusion_scalar_udf__(self) -> object: ...

class QuadBinToChildren:
    def __init__(self) -> None: ...
    def __datafusion_scalar_udf__(self) -> object: ...

class QuadBinResolution:
    def __init__(self) -> None: ...
    def __datafusion_scalar_udf__(self) -> object: ...

class QuadBinToSibling:
    def __init__(self) -> None: ...
    def __datafusion_scalar_udf__(self) -> object: ...

class QuadBinKRing:
    def __init__(self) -> None: ...
    def __datafusion_scalar_udf__(self) -> object: ...

class QuadBinToBBOXMercator:
    def __init__(self) -> None: ...
    def __datafusion_scalar_udf__(self) -> object: ...

class QuadBinToBBOXWGS84:
    def __init__(self) -> None: ...
    def __datafusion_scalar_udf__(self) -> object: ...

class QuadBinToLonLat:
    def __init__(self) -> None: ...
    def __datafusion_scalar_udf__(self) -> object: ...

class QuadBinToPixelXY:
    def __init__(self) -> None: ...
    def __datafusion_scalar_udf__(self) -> object: ...

class QuadBinToWKT:
    def __init__(self) -> None: ...
    def __datafusion_scalar_udf__(self) -> object: ...
    
class QuadBinToGeoJSON:
    def __init__(self) -> None: ...
    def __datafusion_scalar_udf__(self) -> object: ...
