from typing import Literal

class DecompressTile:
    def __init__(self) -> None: ...
    def __datafusion_scalar_udf__(self) -> object: ...

class DecodeTile:
    def __init__(self) -> None: ...
    def __datafusion_scalar_udf__(self) -> object: ...

class NativeTile:
    def __init__(self) -> None: ...
    def __datafusion_scalar_udf__(self) -> object: ...

class RaquetPixel:
    def __init__(self) -> None: ...
    def __datafusion_scalar_udf__(self) -> object: ...

class StatisticsTile:
    def __init__(self) -> None: ...
    def __datafusion_scalar_udf__(self) -> object: ...